
export const GET_POST='GET_POST'
export const LOAD_POST='LOAD_POST'
export const ERROR_POST='ERROR_POST'
export const GET_SINGLE_POST='GET_SINGLE_POST'
export const UPDATE_POST='UPDATE_POST'
export const DELETE_POST='DELETE_POST'
export const CREATE_POST='CREATE_POST'

export const GET_AUCTION_POST='GET_AUCTION_POST'
export const GET_USERS_SUBCAT='GET_USERS_SUBCAT'
export const GET_USERS_AUCTIONLIST='GET_USERS_SUBCAT'




export const LOAD_POST_SUBCAT='LOAD_POST_SUBCAT'
export const ERROR_POST_SUBCAT='ERROR_POST_SUBCAT'


export const LOAD_POST_AUCTIONLIST='LOAD_POST_AUCTIONLIST'
export const ERROR_POST_AUCTIONLIST='ERROR_POST_AUCTIONLIST'
